name = "ElectricalEngineering"
uuid = "84e62fa8-74a0-5990-9214-c45bd74ae4d7"
authors = ["Christian Kral <dr.christian.kral@gmail.com>"]
version = "0.4.4"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"
